name: mercure
type: golang:1.18
source:
    root: mercure
variables:
  env:
    MERCURE_VERSION: "0.14.0"
    SERVER_NAME: :8888
    MERCURE_PUBLISHER_JWT_KEY: '!ChangeMe!'
    MERCURE_SUBSCRIBER_JWT_KEY: '!ChangeMe!'
disk: 1024
mounts:
  'db':
    source: local
    source_path: db
  "/.local": { source: local, source_path: .local }
  "/.config": { source: local, source_path: .config }
hooks:
    build: |
      #Install Mercure using cache
      MERCUREVERSION=0.13.0
      FILE="mercure_${MERCUREVERSION}_Linux_x86_64.tar.gz"
      if [ ! -f "$PLATFORM_CACHE_DIR/$FILE" ]; then
        URL="https://github.com/dunglas/mercure/releases/download/v${MERCUREVERSION}/$FILE"
        echo "Downloading $URL"
        wget -O "$PLATFORM_CACHE_DIR/$FILE" $URL
      else
        echo "Found $FILE in cache, using cache"
      fi
      file $PLATFORM_CACHE_DIR/$FILE
      tar xvzf $PLATFORM_CACHE_DIR/$FILE
    deploy: |
#      corepack ./mercure run -config Caddyfile.platform_sh
web:
    commands:
        start: ./mercure run -config Caddyfile.platform_sh
    locations:
        /:
            allow: true
            passthru: true
            request_buffering:
              enabled: false