name: mercure
  
type: golang:1.11
relationships:
  kafka: "kafka:kafka"
hooks:
  build: |
      #Install Mercure using cache
      MERCUREVERSION=0.9.0
      FILE="mercure_${MERCUREVERSION}_Linux_x86_64.tar.gz"
      URL="https://github.com/dunglas/mercure/releases/download/v${MERCUREVERSION}/$FILE"
      if [ ! -f "$PLATFORM_CACHE_DIR/$FILE" ]; then
      echo "Downloading $URL"
          echo $($PLATFORM_CACHE_DIR/$FILE)
          wget -O "$PLATFORM_CACHE_DIR/$FILE" $URL
      else
          echo "Found $FILE in cache, using cache"
      fi
      pwd
      ls -la /mnt
      file $PLATFORM_CACHE_DIR/$FILE
      tar xvzf $PLATFORM_CACHE_DIR/$FILE
  post_deploy: echo  "Your JWT_KEY is $JWT_KEY"
variables:
  env:
      DEMO: 1
      KAFKA_ADDRS: "kafka.internal:9092"
      KAFKA_TOPIC: platform_sh
      KAFKA_CONSUMER_GROUP: any
      ADDR: "kafka.internal:9092"
      JWT_KEY: "eyJhbGciOiJIUzI1NiJ9.eyJtZXJjdXJlIjp7InB1Ymxpc2giOlsiKiJdLCJzdWJzY3JpYmUiOlsiaHR0cHM6Ly9leGFtcGxlLmNvbS9teS1wcml2YXRlLXRvcGljIiwie3NjaGVtZX06Ly97K2hvc3R9L2RlbW8vYm9va3Mve2lkfS5qc29ubGQiLCIvLndlbGwta25vd24vbWVyY3VyZS9zdWJzY3JpcHRpb25zey90b3BpY317L3N1YnNjcmliZXJ9Il0sInBheWxvYWQiOnsidXNlciI6Imh0dHBzOi8vZXhhbXBsZS5jb20vdXNlcnMvZHVuZ2xhcyIsInJlbW90ZUFkZHIiOiIxMjcuMC4wLjEifX19.KKPIikwUzRuB3DTpVw6ajzwSChwFw5omBMmMcWKiDcM"
      TRANSPORT_URL: "bolt:///app/database/database.db"
mounts:
  "database":
      source: local
      source_path: "database"
web:
  commands:
      start: ./mercure
  locations:
      /mercure:
          root: "mercure/public"
          index:
              - "index.html"
          passthru: true
disk: 1024
