name: mercure
type: golang:1.18
source:
    root: mercure
variables:
  env:
    MERCURE_VERSION: "0.14.0"
    SERVER_NAME: :8888
    MERCURE_PUBLISHER_JWT_KEY: '!ChangeMe!'
    MERCURE_SUBSCRIBER_JWT_KEY: '!ChangeMe!'
disk: 1024
mounts:
  'db':
    source: local
    source_path: db
hooks:
    build: |
      ls -la
      ./mercure
    deploy: |
      ./mercure run -config Caddyfile.platform_sh
web:
#    commands:
#        start: ./mercure run -config Caddyfile.platform_sh
    locations:
        /:
            allow: true
            passthru: true
            request_buffering:
              enabled: false