name: mercure
type: golang:1.18
source:
    root: mercure/mercure
variables:
  env:
    SERVER_NAME: ":2019"
#    MERCURE_TRANSPORT_URL: "bolt:///var/run/mercure.db"
    MERCURE_TRANSPORT_URL: "bolt://mercure.db"
    MERCURE_EXTRA_DIRECTIVES: |
      cors_origins {$PSH_SITE_URL}
      publish_origins {$PSH_SITE_URL}
      subscriptions
      ui true
      debug 1
    GLOBAL_OPTIONS: |
      auto_https off
    MERCURE_VERSION: "0.14.4"
    MERCURE_PUBLISHER_JWT_KEY: "eyJhbGciOiJIUzI1NiJ9.eyJtZXJjdXJlIjp7InB1Ymxpc2giOlsiKiJdLCJzdWJzY3JpYmUiOlsiaHR0cHM6Ly9leGFtcGxlLmNvbS9teS1wcml2YXRlLXRvcGljIiwie3NjaGVtZX06Ly97K2hvc3R9L2RlbW8vYm9va3Mve2lkfS5qc29ubGQiLCIvLndlbGwta25vd24vbWVyY3VyZS9zdWJzY3JpcHRpb25zey90b3BpY317L3N1YnNjcmliZXJ9Il0sInBheWxvYWQiOnsidXNlciI6Imh0dHBzOi8vZXhhbXBsZS5jb20vdXNlcnMvZHVuZ2xhcyIsInJlbW90ZUFkZHIiOiIxMjcuMC4wLjEifX19.KKPIikwUzRuB3DTpVw6ajzwSChwFw5omBMmMcWKiDcM"
    MERCURE_SUBSCRIBER_JWT_KEY: "eyJhbGciOiJIUzI1NiJ9.eyJtZXJjdXJlIjp7InB1Ymxpc2giOlsiKiJdLCJzdWJzY3JpYmUiOlsiaHR0cHM6Ly9leGFtcGxlLmNvbS9teS1wcml2YXRlLXRvcGljIiwie3NjaGVtZX06Ly97K2hvc3R9L2RlbW8vYm9va3Mve2lkfS5qc29ubGQiLCIvLndlbGwta25vd24vbWVyY3VyZS9zdWJzY3JpcHRpb25zey90b3BpY317L3N1YnNjcmliZXJ9Il0sInBheWxvYWQiOnsidXNlciI6Imh0dHBzOi8vZXhhbXBsZS5jb20vdXNlcnMvZHVuZ2xhcyIsInJlbW90ZUFkZHIiOiIxMjcuMC4wLjEifX19.KKPIikwUzRuB3DTpVw6ajzwSChwFw5omBMmMcWKiDcM"
disk: 1024
mounts:
  'db':
    source: local
    source_path: db
  "/.local": { source: local, source_path: .local }
  "/.config": { source: local, source_path: .config }
hooks:
    build: |
      #Install Mercure using cache
      MERCUREVERSION=0.14.4
      FILE="mercure_${MERCUREVERSION}_Linux_x86_64.tar.gz"
      if [ ! -f "$PLATFORM_CACHE_DIR/$FILE" ]; then
        URL="https://github.com/dunglas/mercure/releases/download/v${MERCUREVERSION}/$FILE"
        echo "Downloading $URL"
        wget -O "$PLATFORM_CACHE_DIR/$FILE" $URL
      else
        echo "Found $FILE in cache, using cache"
      fi
      file $PLATFORM_CACHE_DIR/$FILE
      tar xvzf $PLATFORM_CACHE_DIR/$FILE
web:
    commands:
        start: ./mercure run --config Caddyfile.platform_sh
    locations:
        /:
            allow: true
            passthru: true
            request_buffering:
              enabled: false